-- Intake session and submission identity.
--
-- Two identifiers enter the model, both UUIDs generated by the browser:
--
--   clients.sessionId        so one visit reuses one client row instead of
--                            creating a new one every time someone continues
--   intakes.submissionId     so retrying after a failed response returns the
--                            intake already stored rather than writing a
--                            second copy of the same answers
--
-- plus one column that records a real answer rather than an empty one:
--
--   client_preferences.openToGuidance   the person said they are not yet sure
--                            what kind of conversation they want
--
-- The two new columns are NOT NULL with no default, which is what Prisma's own
-- migration for this change would produce — and which fails outright on any
-- database that already holds a client or an intake. They are therefore added
-- as nullable, backfilled with a distinct value per row, and only then made
-- required. The result is identical to the generated version on an empty
-- database, and safe on a populated one.

-- AlterTable
ALTER TABLE "client_preferences" ADD COLUMN "openToGuidance" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "clients" ADD COLUMN "sessionId" UUID;

-- AlterTable
ALTER TABLE "intakes" ADD COLUMN "submissionId" UUID;

-- Backfill. gen_random_uuid() has been built into PostgreSQL since 13, so this
-- needs no extension.
UPDATE "clients" SET "sessionId" = gen_random_uuid() WHERE "sessionId" IS NULL;
UPDATE "intakes" SET "submissionId" = gen_random_uuid() WHERE "submissionId" IS NULL;

-- AlterTable
ALTER TABLE "clients" ALTER COLUMN "sessionId" SET NOT NULL;

-- AlterTable
ALTER TABLE "intakes" ALTER COLUMN "submissionId" SET NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "clients_sessionId_key" ON "clients"("sessionId");

-- CreateIndex
CREATE UNIQUE INDEX "intakes_submissionId_key" ON "intakes"("submissionId");
